<?php

namespace EvenementBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function last()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from(' EvenementBundle:Notification', 'u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults(3);


        return $qb->getQuery()->getResult();
    }
}
