users_index:
    path:     /
    defaults: { _controller: "schoolBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "schoolBundle:Users:show" }
    methods:  GET


statistics_user:
    path:     /user/stat
    defaults: { _controller: "UserBundle:Default:statistiqueUser"}


