<?php

namespace SubjectsBundle\Repository;

/**
 * QQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
