<?php

namespace schoolBundle\Repository;

use Doctrine\ORM\Query\Expr\Select;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClassDQL($name)
    {
        $Query=$this->getEntityManager()
            ->createQuery("select c from schoolBundle:Classe c where c.name LIKE :name")
            ->setParameter('name','%'.$name.'%');
        return $Query->getResult();
    }

}
