<?php

namespace schoolBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function listStudents(): array
    {
        return $this->createQueryBuilder('user')
            ->where()
            ->getQuery()->getResult();
    }
}
