<?php

namespace schoolBundle\Repository;

use Doctrine\ORM\Query\Expr\Select;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListeEtdiant()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT dintinct n.etudiant FROM schoolBundle:Note n ");
        return $query->getResult();
    }

}
