<?php

namespace schoolBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
 * @param string $role
 *
 * @return array
 */
    public function findByRole($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('schoolBundle:Users', 'u')
            ->where('u.roles LIKE :roles')->andWhere('u.classeetd IS NULL')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }

    public function findByRoleClass($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('schoolBundle:Users', 'u')
            ->where('u.roles LIKE :roles')->andWhere('u.classeetd IS NOT NULL')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }
    public function findByRoleNot($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('schoolBundle:Users', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }

    public function findStudentClassDQL($name,$role)
    {
        $Query=$this->getEntityManager()
            ->createQuery("select u from schoolBundle:Users u JOIN schoolBundle:Classe c with c.id=u.classeetd where c.id LIKE :name and u.roles LIKE :roles")
            ->setParameter('name','%'.$name.'%')
            ->setParameter('roles', '%"'.$role.'"%');
        return $Query->getResult();
    }
    public function findTeacherClassDQL($name)
    {
        $Query=$this->getEntityManager()
            ->createQuery("select u from ClassBundle:Classeenseignantmatiere u JOIN schoolBundle:Classe c with c.id=u.idClass where c.id LIKE :name ")
            ->setParameter('name','%'.$name.'%');
        return $Query->getResult();
    }
}
