<?php

namespace SubjectsBundle\Repository;

/**
 * ChaptersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChaptersRepository extends \Doctrine\ORM\EntityRepository
{
}
